baseURL: "https://kazemcodes.ir"
title: KazemCodes
paginate: 5
theme: PaperMod


enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
# googleAnalytics: UA-123-45


minify:
  disableXML: true
  # minifyOutput: true

languages:
  en:
    languageName: "English"
    weight: 1
    taxonomies:
      category: categories
      tag: tags
      series: series
    menu:
      main:
        - name: Blog Archive
          url: archives
          weight: 5
        - name: Projects
          url: projects
          weight: 10
        - name: Search
          url: search/
          weight: 10
        - name: Tags
          url: tags/
          weight: 10
        - name: Github
          url: https://github.com/kazemcodes

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  description: "kazemcodes - Kazem's personal website"
  author: Kazemcodes


  defaultTheme: auto
  # disableThemeToggle: true
  ShowShareButtons: true
  ShowReadingTime: true
  # disableSpecial1stPost: true
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: true
  ShowToc: true
  # comments: false
  images: ["hdhr.png"]

  profileMode:
    enabled: true
    title: "Hello there \U0001F44B"
    subtitle: "Welcome to my **personal website**! - Here you can find out all about me!"
    imageUrl: "/profile.jpg"
    imageTitle: my image
    # imageWidth: 120
    # imageHeight: 120
    buttons:
      - name: My blog
        url: archives
      - name: My projects
        url: projects

  homeInfoParams:
    Title: "Hello there \U0001F44B"
    Content: >
      Welcome to my **personal website**!
  socialIcons:
    - name: GitHub
      url: "https://github.com/kazemcodes"
    - name: "kofi"
      title: "nowpayments"
      url: "https://nowpayments.io/donation/kazemcodes"

  editPost:
    URL: "https://github.com/kazemcodes/kazemcodes.github.io/tree/master/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link



  assets:
    disableHLJS: true
    favicon: "favicon.ico"
    favicon16x16: "favicon-32x32.png"
    favicon32x32: "favicon-32x32.png"
    apple_touch_icon: "apple-touch-icon.png"
    safari_pinned_tab: "safari_pinned_tab.svg"
    theme_color: "#404040"
    msapplication_TileColor: "#404040"


markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false

privacy:
  vimeo:
    disabled: false
    simple: true

  twitter:
    disabled: false
    enableDNT: true
    simple: true

  instagram:
    disabled: false
    simple: true

  youtube:
    disabled: false
    privacyEnhanced: true

services:
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true
